### ISSUE TITLE
Link ngMA recommendations to pages in this wiki

### ISSUE THREAD

**Issue by ellamaolson** [ellamaolson/ngMigration-Forum#3]
**ToDo**
After running [ngma](https://www.npmjs.com/package/ngma), it would be helpful to link to page on this wiki for each of the recommendations as to guide the user on what to do next. 

**Example**
Your Recommendation
  * App contains $rootScope, please refactor rootScope into services. ***Visit http://github.com/....$rootScope to learn how to do this.***
  * App contains $compile, please rewrite compile to eliminate dynamic feature of templates. ***Visit http://github.com/....$compile to learn how to do this.***

**Comment by wizardion** [comment]
@ellamaolson It would be really helpful if you can post here an existing page of the **$rootScope** recommendations to an article where we can read. I'm struggling to find a way to eliminate the $rootScope usage and move it into services if I still use the broadcast events in my AngularJS before the update.

**Comment by wimpog** [comment]
@ellamaolson it would definitely be nice to provide an example of how to refactor $rootScope. The github links in your post don't work.
