### ISSUE TITLE
Currently using gulp with angularjs ap - guides to move to webpack?

### ISSUE THREAD

**Issue by BobDankert** [ellamaolson/ngMigration-Forum#9]
We currently use gulp with our angularjs application, and are working on getting it ready for upgrading via ngUpgrade. One of those tasks is moving to WebPack, however we don't have a lot of experience with this yet. Are there any good guides on setting up WebPack with an AngularJS project that is intended to be used with ngUpgrade and Angular?

Thanks!

**Comment by pankaj28843** [comment]
Hi Bob,

You can start using `@angular/cli` if you don't have a custom webpack setup till now.

Here is a step by step guide on using `@angular/cli` - https://joelbinn.gitbooks.io/hybrid-angular-angularjs-application-with-angular/content/ch1-making-the-hybrid.html

Here is a success story by someone who started with above guide - https://medium.com/@roelofjanelsinga/angularjs-angular-v6-hybrid-finally-97ac37087de1

 If you want to have a custom webpack config then you can find one of the many guides, e.g. [this one](https://joelbinn.gitbooks.io/hybrid-angular-angularjs-application-with-angular/content/ch1-making-the-hybrid.html). I would recommend you to learn about webpack fundamentals as well if you chose to have a custom config.

P.S. - I am also a beginner in ngUpgrade and migration process.

**Comment by BobDankert** [comment]
Thanks so much - that's some great resources I hadn't previously seen. I'll go through those and post back if I run into any issues. Thanks!
